In [1]:
from pathlib import Path
import time

import pandas as pd
import joblib

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    log_loss
)

SEED = 42

In [2]:
PROJECT_ROOT = Path(r"C:\Case Study Trees\HomeCreditStudy")

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
ARTIFACT_DIR = PROJECT_ROOT / "artifacts"
RESULT_DIR = PROJECT_ROOT / "results"

ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
RESULT_DIR.mkdir(parents=True, exist_ok=True)


y_train = pd.read_csv(
    PROCESSED_DIR / "engineered" / "y_train.csv"
)["TARGET"]

y_valid = pd.read_csv(
    PROCESSED_DIR / "engineered" / "y_valid.csv"
)["TARGET"]

print("Training labels:", len(y_train))
print("Validation labels:", len(y_valid))

Training labels: 215256
Validation labels: 46127

In [3]:
X_train = pd.read_csv(
    PROCESSED_DIR / "engineered" / "X_train.csv",
    dtype="float32"
)

X_valid = pd.read_csv(
    PROCESSED_DIR / "engineered" / "X_valid.csv",
    dtype="float32"
)

assert len(X_train) == len(y_train)
assert len(X_valid) == len(y_valid)
assert X_train.columns.equals(X_valid.columns)

print("Training features:", X_train.shape)
print("Validation features:", X_valid.shape)

Training features: (215256, 320)
Validation features: (46127, 320)

In [4]:
rf_engineered = RandomForestClassifier(
    n_estimators=100,
    max_depth=15,
    min_samples_leaf=5,
    random_state=SEED,
    n_jobs=4
)

start_time = time.perf_counter()

rf_engineered.fit(X_train, y_train)

rf_engineered_fit_seconds = time.perf_counter() - start_time

print(
    "Training time:",
    round(rf_engineered_fit_seconds, 2),
    "seconds"
)

Training time: 35.71 seconds

In [5]:
start_time = time.perf_counter()

valid_probability = rf_engineered.predict_proba(X_valid)[:, 1]

prediction_seconds = time.perf_counter() - start_time

rf_engineered_results = {
    "Model": "Random Forest",
    "Feature_Set": "Engineered",
    "ROC_AUC": roc_auc_score(y_valid, valid_probability),
    "Average_Precision": average_precision_score(
        y_valid, valid_probability
    ),
    "Log_Loss": log_loss(y_valid, valid_probability),
    "Fit_Seconds": rf_engineered_fit_seconds,
    "Prediction_Seconds": prediction_seconds
}

display(pd.DataFrame([rf_engineered_results]).round(4))

joblib.dump(
    rf_engineered,
    ARTIFACT_DIR / "rf_engineered_baseline.joblib"
)

pd.DataFrame([rf_engineered_results]).to_csv(
    RESULT_DIR / "rf_engineered_baseline_validation.csv",
    index=False
)

,Model,Feature_Set,ROC_AUC,Average_Precision,Log_Loss,Fit_Seconds,Prediction_Seconds
0,Random Forest,Engineered,0.7429,0.2342,0.2541,35.7073,0.4062

In [6]:
X_train = pd.read_csv(
    PROCESSED_DIR / "engineered_filtered" / "X_train.csv",
    dtype="float32"
)

X_valid = pd.read_csv(
    PROCESSED_DIR / "engineered_filtered" / "X_valid.csv",
    dtype="float32"
)

assert len(X_train) == len(y_train)
assert len(X_valid) == len(y_valid)
assert X_train.columns.equals(X_valid.columns)

rf_filtered = RandomForestClassifier(
    n_estimators=100,
    max_depth=15,
    min_samples_leaf=5,
    random_state=SEED,
    n_jobs=4
)

start_time = time.perf_counter()

rf_filtered.fit(X_train, y_train)

rf_filtered_fit_seconds = time.perf_counter() - start_time

print("Training features:", X_train.shape)
print("Training time:", round(rf_filtered_fit_seconds, 2), "seconds")

Training features: (215256, 264)
Training time: 34.75 seconds

In [ ]:
start_time = time.perf_counter()

valid_probability = rf_filtered.predict_proba(X_valid)[:, 1]

prediction_seconds = time.perf_counter() - start_time

rf_filtered_results = {
    "Model": "Random Forest",
    "Feature_Set": "Engineered + filtered",
    "ROC_AUC": roc_auc_score(y_valid, valid_probability),
    "Average_Precision": average_precision_score(
        y_valid, valid_probability
    ),
    "Log_Loss": log_loss(y_valid, valid_probability),
    "Fit_Seconds": rf_filtered_fit_seconds,
    "Prediction_Seconds": prediction_seconds
}

rf_comparison = pd.DataFrame([
    rf_engineered_results,
    rf_filtered_results
]).sort_values("ROC_AUC", ascending=False)

display(rf_comparison.round(4))


joblib.dump(
    rf_filtered,
    ARTIFACT_DIR / "rf_filtered_baseline.joblib"
)

rf_comparison.to_csv(
    RESULT_DIR / "rf_baseline_comparison.csv",
    index=False
)

,Model,Feature_Set,ROC_AUC,Average_Precision,Log_Loss,Fit_Seconds,Prediction_Seconds
1,Random Forest,Engineered + filtered,0.7464,0.2358,0.2527,34.7467,0.3759
0,Random Forest,Engineered,0.7429,0.2342,0.2541,35.7073,0.4062

In [9]:
import optuna

X_train = pd.read_csv(
    PROCESSED_DIR / "engineered_filtered" / "X_train.csv",
    dtype="float32"
)

X_valid = pd.read_csv(
    PROCESSED_DIR / "engineered_filtered" / "X_valid.csv",
    dtype="float32"
)

STUDY_DIR = PROJECT_ROOT / "studies"
STUDY_DIR.mkdir(parents=True, exist_ok=True)


def objective(trial):
    model = RandomForestClassifier(
        n_estimators=trial.suggest_int(
            "n_estimators", 100, 500, step=100
        ),
        max_depth=trial.suggest_int("max_depth", 8, 30),
        min_samples_split=trial.suggest_int(
            "min_samples_split", 2, 20
        ),
        min_samples_leaf=trial.suggest_int(
            "min_samples_leaf", 1, 20
        ),
        max_features=trial.suggest_categorical(
            "max_features", ["sqrt", 0.3, 0.6]
        ),
        class_weight=trial.suggest_categorical(
            "class_weight", [None, "balanced"]
        ),
        random_state=SEED,
        n_jobs=4
    )

    start = time.perf_counter()

    model.fit(X_train, y_train)
    probability = model.predict_proba(X_valid)[:, 1]

    trial.set_user_attr(
        "fit_predict_seconds",
        time.perf_counter() - start
    )

    return roc_auc_score(y_valid, probability)


database_path = (STUDY_DIR / "home_credit_optuna.db").resolve()

study = optuna.create_study(
    study_name="rf_engineered_filtered_v1",
    storage="sqlite:///" + database_path.as_posix(),
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=SEED),
    load_if_exists=True
)

tuning_start = time.perf_counter()

study.optimize(
    objective,
    timeout=30 * 60,
    n_jobs=1,
    gc_after_trial=True
)

rf_tuning_seconds = time.perf_counter() - tuning_start

study.trials_dataframe().to_csv(
    RESULT_DIR / "rf_optuna_trials.csv",
    index=False
)

print("Best validation ROC-AUC:", study.best_value)
print("Best parameters:", study.best_params)
print("Tuning seconds:", round(rf_tuning_seconds, 2))

c:\Users\gdeep\anaconda3\envs\100DaysML_311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-10-16 00:15:03,798] A new study created in RDB with name: rf_engineered_filtered_v1
[I 2026-10-16 00:16:26,219] Trial 0 finished with value: 0.7514563028835408 and parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 15, 'min_samples_leaf': 12, 'max_features': 'sqrt', 'class_weight': None}. Best is trial 0 with value: 0.7514563028835408.
[I 2026-10-16 00:17:29,267] Trial 1 finished with value: 0.7360237023437811 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 20, 'min_samples_leaf': 17, 'max_features': 'sqrt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7514563028835408.
[I 2026-10-16 00:30:28,730] Trial 2 finished with value: 0.743206469872364 and parameters: {'n_estimators': 300, 'max_depth': 14, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_features': 0.6, 'class_weight': None}. Best is trial 0 with value: 0.7514563028835408.
[I 2026-10-16 00:48:15,681] Trial 3 finished with value: 0.7432630975054382 and parameters: {'n_estimators': 300, 'max_depth': 21, 'min_samples_split': 2, 'min_samples_leaf': 13, 'max_features': 0.6, 'class_weight': None}. Best is trial 0 with value: 0.7514563028835408.

Best validation ROC-AUC: 0.7514563028835408
Best parameters: {'n_estimators': 200, 'max_depth': 29, 'min_samples_split': 15, 'min_samples_leaf': 12, 'max_features': 'sqrt', 'class_weight': None}
Tuning seconds: 1991.99

In [10]:
print("Best trial:", study.best_trial.number)
print("Best validation ROC-AUC:", round(study.best_value, 4))

print("\nBest parameters:")
for parameter, value in study.best_params.items():
    print(f"{parameter}: {value}")

print("\nFiltered baseline ROC-AUC:")
print(round(rf_filtered_results["ROC_AUC"], 4))

improvement = study.best_value - rf_filtered_results["ROC_AUC"]
print("\nROC-AUC improvement:", round(improvement, 4))

Best trial: 0
Best validation ROC-AUC: 0.7515

Best parameters:
n_estimators: 200
max_depth: 29
min_samples_split: 15
min_samples_leaf: 12
max_features: sqrt
class_weight: None

Filtered baseline ROC-AUC:
0.7464

ROC-AUC improvement: 0.0051

In [11]:
rf_tuned = RandomForestClassifier(
    **study.best_params,
    random_state=SEED,
    n_jobs=4
)

start_time = time.perf_counter()

rf_tuned.fit(X_train, y_train)

rf_tuned_fit_seconds = time.perf_counter() - start_time

start_time = time.perf_counter()

valid_probability = rf_tuned.predict_proba(X_valid)[:, 1]

prediction_seconds = time.perf_counter() - start_time

rf_tuned_results = {
    "Model": "Random Forest",
    "Version": "Tuned",
    "Feature_Set": "Engineered + filtered",
    "ROC_AUC": roc_auc_score(y_valid, valid_probability),
    "Average_Precision": average_precision_score(
        y_valid, valid_probability
    ),
    "Log_Loss": log_loss(y_valid, valid_probability),
    "Fit_Seconds": rf_tuned_fit_seconds,
    "Prediction_Seconds": prediction_seconds
}

display(pd.DataFrame([rf_tuned_results]).round(4))

joblib.dump(
    rf_tuned,
    ARTIFACT_DIR / "rf_filtered_tuned.joblib"
)

pd.DataFrame([rf_tuned_results]).to_csv(
    RESULT_DIR / "rf_tuned_validation.csv",
    index=False
)

pd.Series(study.best_params, name="Value").to_csv(
    RESULT_DIR / "rf_best_parameters.csv",
    index_label="Parameter"
)

,Model,Version,Feature_Set,ROC_AUC,Average_Precision,Log_Loss,Fit_Seconds,Prediction_Seconds
0,Random Forest,Tuned,Engineered + filtered,0.7515,0.2402,0.2506,76.8446,1.1124

## XGBOOST

In [13]:
from xgboost import XGBClassifier

X_train = pd.read_csv(
    PROCESSED_DIR / "engineered" / "X_train.csv",
    dtype="float32"
)

X_valid = pd.read_csv(
    PROCESSED_DIR / "engineered" / "X_valid.csv",
    dtype="float32"
)

assert len(X_train) == len(y_train)
assert len(X_valid) == len(y_valid)
assert X_train.columns.equals(X_valid.columns)

print("Training:", X_train.shape)
print("Validation:", X_valid.shape)

Training: (215256, 320)
Validation: (46127, 320)

In [14]:
xgb_engineered = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=1.0,
    colsample_bytree=1.0,
    objective="binary:logistic",
    eval_metric="auc",
    tree_method="hist",
    random_state=SEED,
    n_jobs=4
)

start_time = time.perf_counter()

xgb_engineered.fit(X_train, y_train)

xgb_engineered_fit_seconds = time.perf_counter() - start_time

print(
    "Training time:",
    round(xgb_engineered_fit_seconds, 2),
    "seconds"
)

Training time: 19.87 seconds

In [15]:
start_time = time.perf_counter()

valid_probability = xgb_engineered.predict_proba(X_valid)[:, 1]

prediction_seconds = time.perf_counter() - start_time

xgb_engineered_results = {
    "Model": "XGBoost",
    "Feature_Set": "Engineered",
    "ROC_AUC": roc_auc_score(y_valid, valid_probability),
    "Average_Precision": average_precision_score(
        y_valid, valid_probability
    ),
    "Log_Loss": log_loss(y_valid, valid_probability),
    "Fit_Seconds": xgb_engineered_fit_seconds,
    "Prediction_Seconds": prediction_seconds
}

display(pd.DataFrame([xgb_engineered_results]).round(4))

joblib.dump(
    xgb_engineered,
    ARTIFACT_DIR / "xgb_engineered_baseline.joblib"
)

pd.DataFrame([xgb_engineered_results]).to_csv(
    RESULT_DIR / "xgb_engineered_baseline_validation.csv",
    index=False
)

,Model,Feature_Set,ROC_AUC,Average_Precision,Log_Loss,Fit_Seconds,Prediction_Seconds
0,XGBoost,Engineered,0.7607,0.2536,0.245,19.8692,0.1865

In [16]:
X_train = pd.read_csv(
    PROCESSED_DIR / "engineered_filtered" / "X_train.csv",
    dtype="float32"
)

X_valid = pd.read_csv(
    PROCESSED_DIR / "engineered_filtered" / "X_valid.csv",
    dtype="float32"
)

assert len(X_train) == len(y_train)
assert len(X_valid) == len(y_valid)
assert X_train.columns.equals(X_valid.columns)

# Copy the engineered baseline settings, without copying fitted trees
xgb_filtered = XGBClassifier(**xgb_engineered.get_params())

start_time = time.perf_counter()

xgb_filtered.fit(X_train, y_train)

xgb_filtered_fit_seconds = time.perf_counter() - start_time

print("Training features:", X_train.shape)
print(
    "Training time:",
    round(xgb_filtered_fit_seconds, 2),
    "seconds"
)

Training features: (215256, 264)
Training time: 24.11 seconds

In [17]:
start_time = time.perf_counter()

valid_probability = xgb_filtered.predict_proba(X_valid)[:, 1]

prediction_seconds = time.perf_counter() - start_time

xgb_filtered_results = {
    "Model": "XGBoost",
    "Feature_Set": "Engineered + filtered",
    "ROC_AUC": roc_auc_score(y_valid, valid_probability),
    "Average_Precision": average_precision_score(
        y_valid, valid_probability
    ),
    "Log_Loss": log_loss(y_valid, valid_probability),
    "Fit_Seconds": xgb_filtered_fit_seconds,
    "Prediction_Seconds": prediction_seconds
}

xgb_comparison = pd.DataFrame([
    xgb_engineered_results,
    xgb_filtered_results
]).sort_values("ROC_AUC", ascending=False)

display(xgb_comparison.round(4))

joblib.dump(
    xgb_filtered,
    ARTIFACT_DIR / "xgb_filtered_baseline.joblib"
)

xgb_comparison.to_csv(
    RESULT_DIR / "xgb_baseline_comparison.csv",
    index=False
)

,Model,Feature_Set,ROC_AUC,Average_Precision,Log_Loss,Fit_Seconds,Prediction_Seconds
1,XGBoost,Engineered + filtered,0.7616,0.2530,0.2449,24.1122,0.2012
0,XGBoost,Engineered,0.7607,0.2536,0.2450,19.8692,0.1865

In [21]:
def xgb_objective(trial):
    model = XGBClassifier(
        n_estimators=trial.suggest_int(
            "n_estimators", 200, 1000, step=100
        ),
        learning_rate=trial.suggest_float(
            "learning_rate", 0.01, 0.15, log=True
        ),
        max_depth=trial.suggest_int("max_depth", 3, 9),
        min_child_weight=trial.suggest_float(
            "min_child_weight", 1, 30, log=True
        ),
        subsample=trial.suggest_float("subsample", 0.6, 1.0),
        colsample_bytree=trial.suggest_float(
            "colsample_bytree", 0.6, 1.0
        ),
        reg_alpha=trial.suggest_float(
            "reg_alpha", 1e-4, 10, log=True
        ),
        reg_lambda=trial.suggest_float(
            "reg_lambda", 0.1, 20, log=True
        ),
        objective="binary:logistic",
        eval_metric="auc",
        tree_method="hist",
        random_state=SEED,
        n_jobs=4
    )

    start = time.perf_counter()

    model.fit(X_train, y_train)
    probability = model.predict_proba(X_valid)[:, 1]

    trial.set_user_attr(
        "fit_predict_seconds",
        time.perf_counter() - start
    )

    return roc_auc_score(y_valid, probability)


tuning_start = time.perf_counter()

xgb_study.optimize(
    xgb_objective,
    timeout=30 * 60,
    n_jobs=1,
    gc_after_trial=True
)

xgb_tuning_seconds = time.perf_counter() - tuning_start

xgb_study.trials_dataframe().to_csv(
    RESULT_DIR / "xgb_optuna_trials.csv",
    index=False
)

print("Best validation ROC-AUC:", xgb_study.best_value)
print("Best parameters:", xgb_study.best_params)
print("Tuning seconds:", round(xgb_tuning_seconds, 2))

[I 2026-10-16 01:03:20,202] Trial 0 finished with value: 0.7437435141348574 and parameters: {'n_estimators': 500, 'learning_rate': 0.13125830316209655, 'max_depth': 8, 'min_child_weight': 7.6611007077713635, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'reg_alpha': 0.00019517224641449495, 'reg_lambda': 9.842315738502599}. Best is trial 0 with value: 0.7437435141348574.
[I 2026-10-16 01:03:48,570] Trial 1 finished with value: 0.7632560051825367 and parameters: {'n_estimators': 700, 'learning_rate': 0.06803900745073706, 'max_depth': 3, 'min_child_weight': 27.08160864249967, 'subsample': 0.9329770563201687, 'colsample_bytree': 0.6849356442713105, 'reg_alpha': 0.0008111941985431928, 'reg_lambda': 0.26425260575499165}. Best is trial 1 with value: 0.7632560051825367.
[I 2026-10-16 01:04:12,946] Trial 2 finished with value: 0.7645640769089128 and parameters: {'n_estimators': 400, 'learning_rate': 0.04141536110538596, 'max_depth': 6, 'min_child_weight': 2.6926552514864723, 'subsample': 0.8447411578889518, 'colsample_bytree': 0.6557975442608167, 'reg_alpha': 0.0028888383623653178, 'reg_lambda': 0.6966418981413739}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:04:43,440] Trial 3 finished with value: 0.7613951174289418 and parameters: {'n_estimators': 600, 'learning_rate': 0.0838375512850209, 'max_depth': 4, 'min_child_weight': 5.748924681991978, 'subsample': 0.836965827544817, 'colsample_bytree': 0.6185801650879991, 'reg_alpha': 0.10907475835157694, 'reg_lambda': 0.24682044079890128}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:04:59,490] Trial 4 finished with value: 0.7513953847985089 and parameters: {'n_estimators': 200, 'learning_rate': 0.13060986669773664, 'max_depth': 9, 'min_child_weight': 15.635108708133458, 'subsample': 0.7218455076693483, 'colsample_bytree': 0.6390688456025535, 'reg_alpha': 0.2637333993381525, 'reg_lambda': 1.0299214204601976}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:05:14,318] Trial 5 finished with value: 0.7595995712005157 and parameters: {'n_estimators': 300, 'learning_rate': 0.03822726574649208, 'max_depth': 3, 'min_child_weight': 22.038218939289873, 'subsample': 0.7035119926400067, 'colsample_bytree': 0.8650089137415928, 'reg_alpha': 0.003618723330959626, 'reg_lambda': 1.572867419497858}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:06:03,275] Trial 6 finished with value: 0.762448310977936 and parameters: {'n_estimators': 600, 'learning_rate': 0.016497027917250065, 'max_depth': 9, 'min_child_weight': 13.962563737015762, 'subsample': 0.9757995766256756, 'colsample_bytree': 0.9579309401710595, 'reg_alpha': 0.09761125443110447, 'reg_lambda': 13.220877067405619}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:06:18,118] Trial 7 finished with value: 0.7465530698953191 and parameters: {'n_estimators': 200, 'learning_rate': 0.017001754132211097, 'max_depth': 3, 'min_child_weight': 3.0237950125584745, 'subsample': 0.7554709158757928, 'colsample_bytree': 0.7085396127095583, 'reg_alpha': 1.3921548533046495, 'reg_lambda': 0.6620642015198966}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:06:45,683] Trial 8 finished with value: 0.7619957047098055 and parameters: {'n_estimators': 400, 'learning_rate': 0.043477055106943, 'max_depth': 3, 'min_child_weight': 15.30883741573138, 'subsample': 0.6298202574719083, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.7264803074826727, 'reg_lambda': 0.28658321062461245}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:07:06,118] Trial 9 finished with value: 0.7613058348652094 and parameters: {'n_estimators': 200, 'learning_rate': 0.09100328259258599, 'max_depth': 7, 'min_child_weight': 11.935262708510537, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'reg_alpha': 0.006199100007802264, 'reg_lambda': 0.18476435128841198}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:07:35,832] Trial 10 finished with value: 0.7483569088866069 and parameters: {'n_estimators': 300, 'learning_rate': 0.12266021130077727, 'max_depth': 8, 'min_child_weight': 1.1080588683824826, 'subsample': 0.8932568743724454, 'colsample_bytree': 0.8129152157953983, 'reg_alpha': 0.0001762000510305401, 'reg_lambda': 1.2404653742385348}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:08:37,398] Trial 11 finished with value: 0.7614823323431329 and parameters: {'n_estimators': 700, 'learning_rate': 0.03988871038686803, 'max_depth': 7, 'min_child_weight': 9.259626525905384, 'subsample': 0.8665424158471869, 'colsample_bytree': 0.7205615657453802, 'reg_alpha': 0.0003424282038362617, 'reg_lambda': 0.6273746851521739}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:09:09,116] Trial 12 finished with value: 0.7642036947763737 and parameters: {'n_estimators': 700, 'learning_rate': 0.04295868858656171, 'max_depth': 4, 'min_child_weight': 26.053691570081302, 'subsample': 0.977033818112541, 'colsample_bytree': 0.7276384416042097, 'reg_alpha': 0.0007296933483236938, 'reg_lambda': 0.2743573359895198}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:09:51,301] Trial 13 finished with value: 0.7556378913515963 and parameters: {'n_estimators': 800, 'learning_rate': 0.07357561271523735, 'max_depth': 6, 'min_child_weight': 17.684624629745926, 'subsample': 0.9527595270671589, 'colsample_bytree': 0.7800559478512094, 'reg_alpha': 0.003377447498725827, 'reg_lambda': 0.2675235887027334}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:10:35,405] Trial 14 finished with value: 0.7636668689944597 and parameters: {'n_estimators': 800, 'learning_rate': 0.051885105231686345, 'max_depth': 3, 'min_child_weight': 1.662037360461342, 'subsample': 0.9560449693781474, 'colsample_bytree': 0.6398471741538085, 'reg_alpha': 0.0004500669693525121, 'reg_lambda': 0.1972321994840442}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:11:01,228] Trial 15 finished with value: 0.7641769989826785 and parameters: {'n_estimators': 300, 'learning_rate': 0.045660141239245874, 'max_depth': 6, 'min_child_weight': 5.954259628675485, 'subsample': 0.7863013211066463, 'colsample_bytree': 0.6253944201467758, 'reg_alpha': 0.0005578705574120765, 'reg_lambda': 0.6773771738130008}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:11:18,865] Trial 16 finished with value: 0.7625482610934368 and parameters: {'n_estimators': 300, 'learning_rate': 0.059113742782923556, 'max_depth': 5, 'min_child_weight': 5.074034171349556, 'subsample': 0.9223251051401371, 'colsample_bytree': 0.787459006166573, 'reg_alpha': 0.00029714526620619756, 'reg_lambda': 0.5647630057439191}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:12:19,067] Trial 17 finished with value: 0.7537174692233056 and parameters: {'n_estimators': 800, 'learning_rate': 0.06711404864884142, 'max_depth': 7, 'min_child_weight': 17.193200287350503, 'subsample': 0.8698611953979504, 'colsample_bytree': 0.6349641660274284, 'reg_alpha': 0.0023127112396581994, 'reg_lambda': 1.2161777590721623}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:12:51,399] Trial 18 finished with value: 0.7634943928257513 and parameters: {'n_estimators': 800, 'learning_rate': 0.05509015931093501, 'max_depth': 3, 'min_child_weight': 10.037162691176121, 'subsample': 0.9318010582444332, 'colsample_bytree': 0.7296361144754877, 'reg_alpha': 0.0058249193730671766, 'reg_lambda': 0.8444680740141254}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:13:20,423] Trial 19 finished with value: 0.7628438146552112 and parameters: {'n_estimators': 500, 'learning_rate': 0.02806826266579835, 'max_depth': 4, 'min_child_weight': 8.994076951399057, 'subsample': 0.8956462136672315, 'colsample_bytree': 0.6845300939615244, 'reg_alpha': 0.0028217130798804443, 'reg_lambda': 1.064137612521723}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:13:58,411] Trial 20 finished with value: 0.7596985745668392 and parameters: {'n_estimators': 600, 'learning_rate': 0.04970308062558579, 'max_depth': 7, 'min_child_weight': 10.558807600434314, 'subsample': 0.9708672474184955, 'colsample_bytree': 0.6189564143992226, 'reg_alpha': 0.0006242945704579083, 'reg_lambda': 0.2780466532284757}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:14:17,101] Trial 21 finished with value: 0.7623782705371175 and parameters: {'n_estimators': 200, 'learning_rate': 0.03811251559413142, 'max_depth': 6, 'min_child_weight': 5.052598397575006, 'subsample': 0.7501113914064687, 'colsample_bytree': 0.6279599475262432, 'reg_alpha': 0.00864675542035878, 'reg_lambda': 0.5663844801711615}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:14:54,285] Trial 22 finished with value: 0.7637241109062644 and parameters: {'n_estimators': 600, 'learning_rate': 0.03574186908646043, 'max_depth': 4, 'min_child_weight': 19.264266382835636, 'subsample': 0.9219518244057722, 'colsample_bytree': 0.7705368362210822, 'reg_alpha': 0.00023675194419664884, 'reg_lambda': 0.20879312326700528}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:15:56,480] Trial 23 finished with value: 0.7616492103427921 and parameters: {'n_estimators': 900, 'learning_rate': 0.03926299380584693, 'max_depth': 6, 'min_child_weight': 17.66056347996656, 'subsample': 0.9380673040017422, 'colsample_bytree': 0.7126981000322248, 'reg_alpha': 0.00030307894388541186, 'reg_lambda': 0.3831825941688378}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:16:21,532] Trial 24 finished with value: 0.7591915729672067 and parameters: {'n_estimators': 400, 'learning_rate': 0.08084908276471177, 'max_depth': 6, 'min_child_weight': 5.087909416480545, 'subsample': 0.8358821821430308, 'colsample_bytree': 0.6621708610065717, 'reg_alpha': 0.00036875755548026356, 'reg_lambda': 0.7197588258632253}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:16:46,260] Trial 25 finished with value: 0.7619855026166628 and parameters: {'n_estimators': 400, 'learning_rate': 0.020396475519495708, 'max_depth': 5, 'min_child_weight': 7.475155075207225, 'subsample': 0.8300195417034464, 'colsample_bytree': 0.6609522898043453, 'reg_alpha': 0.00034158905840168003, 'reg_lambda': 0.5646571794214419}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:17:00,845] Trial 26 finished with value: 0.7566828681309737 and parameters: {'n_estimators': 200, 'learning_rate': 0.08748042965930869, 'max_depth': 8, 'min_child_weight': 7.138335578645781, 'subsample': 0.8062917686001345, 'colsample_bytree': 0.6196633366207588, 'reg_alpha': 0.00021142776547494087, 'reg_lambda': 0.36083337464426635}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:17:17,864] Trial 27 finished with value: 0.763688422578576 and parameters: {'n_estimators': 300, 'learning_rate': 0.050295287437089234, 'max_depth': 5, 'min_child_weight': 5.159956548920841, 'subsample': 0.7264953663046387, 'colsample_bytree': 0.6395531892467792, 'reg_alpha': 0.0004476091171869023, 'reg_lambda': 1.934362518842938}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:17:45,483] Trial 28 finished with value: 0.7635071501917575 and parameters: {'n_estimators': 400, 'learning_rate': 0.0405238490595245, 'max_depth': 6, 'min_child_weight': 14.47458290479053, 'subsample': 0.8266043614070606, 'colsample_bytree': 0.6008388049057162, 'reg_alpha': 0.00015643689491576379, 'reg_lambda': 1.818064806656404}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:18:09,990] Trial 29 finished with value: 0.7633398827267177 and parameters: {'n_estimators': 400, 'learning_rate': 0.049475439377366925, 'max_depth': 5, 'min_child_weight': 6.397664516350227, 'subsample': 0.8041993426191347, 'colsample_bytree': 0.6021306534428733, 'reg_alpha': 0.0023845137548279345, 'reg_lambda': 0.5367120614954436}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:18:39,392] Trial 30 finished with value: 0.7640369212674266 and parameters: {'n_estimators': 500, 'learning_rate': 0.04160829339871777, 'max_depth': 5, 'min_child_weight': 1.3516050874378387, 'subsample': 0.85739711470576, 'colsample_bytree': 0.6979684954448568, 'reg_alpha': 0.0032592970545523114, 'reg_lambda': 0.5908394513810771}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:19:05,884] Trial 31 finished with value: 0.7629840981855017 and parameters: {'n_estimators': 400, 'learning_rate': 0.050544141973519, 'max_depth': 6, 'min_child_weight': 2.200272631753469, 'subsample': 0.8829792361218769, 'colsample_bytree': 0.6364574544145741, 'reg_alpha': 0.013084934029301894, 'reg_lambda': 1.5777174995325758}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:19:23,212] Trial 32 finished with value: 0.7606363090455799 and parameters: {'n_estimators': 300, 'learning_rate': 0.07141994707173019, 'max_depth': 6, 'min_child_weight': 2.311735053530967, 'subsample': 0.80767289107767, 'colsample_bytree': 0.6456264484831556, 'reg_alpha': 0.0005723346264681272, 'reg_lambda': 1.3201877350633333}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:19:56,423] Trial 33 finished with value: 0.7631627203079002 and parameters: {'n_estimators': 400, 'learning_rate': 0.026881452952487696, 'max_depth': 5, 'min_child_weight': 3.1623716355952474, 'subsample': 0.8522453820703136, 'colsample_bytree': 0.6475228433532184, 'reg_alpha': 0.004673850938867484, 'reg_lambda': 0.9008164780361101}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:20:31,057] Trial 34 finished with value: 0.7622686882778114 and parameters: {'n_estimators': 400, 'learning_rate': 0.053830882536412536, 'max_depth': 6, 'min_child_weight': 1.0505552091525647, 'subsample': 0.8607911533987421, 'colsample_bytree': 0.6721949393969399, 'reg_alpha': 0.01850168613101382, 'reg_lambda': 0.6256977504817175}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:20:50,708] Trial 35 finished with value: 0.7604181261063825 and parameters: {'n_estimators': 200, 'learning_rate': 0.03206816489834084, 'max_depth': 5, 'min_child_weight': 5.578289630236392, 'subsample': 0.824285346024666, 'colsample_bytree': 0.6100641913102884, 'reg_alpha': 0.000554996793612458, 'reg_lambda': 0.26252072470328647}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:21:15,778] Trial 36 finished with value: 0.7638334968496873 and parameters: {'n_estimators': 400, 'learning_rate': 0.029970782573361256, 'max_depth': 5, 'min_child_weight': 1.5994414964777164, 'subsample': 0.8275749339082339, 'colsample_bytree': 0.6146240144014337, 'reg_alpha': 0.0005342153541364296, 'reg_lambda': 0.2981660981200684}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:21:46,009] Trial 37 finished with value: 0.7623504760077546 and parameters: {'n_estimators': 400, 'learning_rate': 0.053687981166079445, 'max_depth': 6, 'min_child_weight': 1.8551481470285525, 'subsample': 0.8673767889650175, 'colsample_bytree': 0.7086674331481054, 'reg_alpha': 0.004342209634982838, 'reg_lambda': 1.494850703093595}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:22:06,335] Trial 38 finished with value: 0.7630431734343421 and parameters: {'n_estimators': 300, 'learning_rate': 0.04975162225360314, 'max_depth': 6, 'min_child_weight': 1.9131573690986912, 'subsample': 0.7662054883705672, 'colsample_bytree': 0.6510895883535126, 'reg_alpha': 0.0020078469999651846, 'reg_lambda': 0.9769859350797003}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:22:44,332] Trial 39 finished with value: 0.7619673528966459 and parameters: {'n_estimators': 500, 'learning_rate': 0.04737338238922259, 'max_depth': 6, 'min_child_weight': 3.00934353489656, 'subsample': 0.9016699668016042, 'colsample_bytree': 0.6526209872942108, 'reg_alpha': 0.0018669205735785523, 'reg_lambda': 0.41534558206991434}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:23:25,424] Trial 40 finished with value: 0.7637349177789818 and parameters: {'n_estimators': 500, 'learning_rate': 0.031348617849751126, 'max_depth': 6, 'min_child_weight': 2.092418517717131, 'subsample': 0.8187459208439409, 'colsample_bytree': 0.6256684254155371, 'reg_alpha': 0.0025209643393105242, 'reg_lambda': 1.2635941632563912}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:24:00,205] Trial 41 finished with value: 0.7633762803246927 and parameters: {'n_estimators': 500, 'learning_rate': 0.03591090396096561, 'max_depth': 4, 'min_child_weight': 1.7421905375089979, 'subsample': 0.8218378621157971, 'colsample_bytree': 0.6866912473560066, 'reg_alpha': 0.00018227746562232399, 'reg_lambda': 0.2649748389667084}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:24:33,777] Trial 42 finished with value: 0.7640654947275506 and parameters: {'n_estimators': 400, 'learning_rate': 0.042906591138666, 'max_depth': 6, 'min_child_weight': 1.544732680582253, 'subsample': 0.8419343573610536, 'colsample_bytree': 0.6908774223217586, 'reg_alpha': 0.0053207425415327985, 'reg_lambda': 0.37392603590190227}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:25:10,877] Trial 43 finished with value: 0.7638082829242697 and parameters: {'n_estimators': 500, 'learning_rate': 0.045701531713293685, 'max_depth': 5, 'min_child_weight': 1.6821513070287986, 'subsample': 0.8167557985415259, 'colsample_bytree': 0.6928119608220604, 'reg_alpha': 0.004326065973575015, 'reg_lambda': 0.8911324987693128}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:25:47,583] Trial 44 finished with value: 0.7629445595333995 and parameters: {'n_estimators': 400, 'learning_rate': 0.039069326353236, 'max_depth': 6, 'min_child_weight': 1.6781483692610615, 'subsample': 0.803729160319552, 'colsample_bytree': 0.6291741678655203, 'reg_alpha': 0.011037153819508781, 'reg_lambda': 0.6080295214811862}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:26:15,593] Trial 45 finished with value: 0.7634210466787748 and parameters: {'n_estimators': 300, 'learning_rate': 0.03582048602735308, 'max_depth': 6, 'min_child_weight': 1.5380684694183346, 'subsample': 0.8582098539865073, 'colsample_bytree': 0.7276900431809523, 'reg_alpha': 0.001692209005304611, 'reg_lambda': 1.072700924187327}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:26:42,993] Trial 46 finished with value: 0.7636635284580643 and parameters: {'n_estimators': 300, 'learning_rate': 0.04001398928817413, 'max_depth': 6, 'min_child_weight': 3.0085375109181776, 'subsample': 0.8378165501084723, 'colsample_bytree': 0.6759805040027074, 'reg_alpha': 0.0027276416906593538, 'reg_lambda': 0.6595724109581484}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:27:08,933] Trial 47 finished with value: 0.7621036752790402 and parameters: {'n_estimators': 300, 'learning_rate': 0.059493413749809015, 'max_depth': 6, 'min_child_weight': 1.591572302019725, 'subsample': 0.8528239018099152, 'colsample_bytree': 0.6748572696662528, 'reg_alpha': 0.00622126712469669, 'reg_lambda': 0.5034542973923396}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:27:49,474] Trial 48 finished with value: 0.7641764290333408 and parameters: {'n_estimators': 500, 'learning_rate': 0.04199576223340332, 'max_depth': 6, 'min_child_weight': 1.0698412035697804, 'subsample': 0.8609550368671868, 'colsample_bytree': 0.605828538421259, 'reg_alpha': 0.002215214582310974, 'reg_lambda': 0.7068458844017821}. Best is trial 2 with value: 0.7645640769089128.
[I 2026-10-16 01:28:08,096] Trial 49 finished with value: 0.7633886292270071 and parameters: {'n_estimators': 200, 'learning_rate': 0.04806530330166727, 'max_depth': 5, 'min_child_weight': 1.0852039670865392, 'subsample': 0.7923069122685592, 'colsample_bytree': 0.6605825593596392, 'reg_alpha': 0.0011268203446321075, 'reg_lambda': 0.52162298800776}. Best is trial 2 with value: 0.7645640769089128.

Best validation ROC-AUC: 0.7645760838416247
Best parameters: {'n_estimators': 500, 'learning_rate': 0.031210347442980457, 'max_depth': 6, 'min_child_weight': 2.06260932932417, 'subsample': 0.8355766793979985, 'colsample_bytree': 0.7044709053513115, 'reg_alpha': 0.0015054671981229908, 'reg_lambda': 0.4068042227014351}
Tuning seconds: 1829.0

In [22]:
xgb_tuned = XGBClassifier(
    **xgb_study.best_params,
    objective="binary:logistic",
    eval_metric="auc",
    tree_method="hist",
    random_state=SEED,
    n_jobs=4
)

start_time = time.perf_counter()

xgb_tuned.fit(X_train, y_train)

xgb_tuned_fit_seconds = time.perf_counter() - start_time

start_time = time.perf_counter()

valid_probability = xgb_tuned.predict_proba(X_valid)[:, 1]

prediction_seconds = time.perf_counter() - start_time

xgb_tuned_results = {
    "Model": "XGBoost",
    "Version": "Tuned",
    "Feature_Set": "Engineered + filtered",
    "ROC_AUC": roc_auc_score(y_valid, valid_probability),
    "Average_Precision": average_precision_score(
        y_valid, valid_probability
    ),
    "Log_Loss": log_loss(y_valid, valid_probability),
    "Fit_Seconds": xgb_tuned_fit_seconds,
    "Prediction_Seconds": prediction_seconds,
    "Tuning_Seconds": xgb_tuning_seconds
}

display(pd.DataFrame([xgb_tuned_results]).round(4))

joblib.dump(
    xgb_tuned,
    ARTIFACT_DIR / "xgb_filtered_tuned.joblib"
)

pd.DataFrame([xgb_tuned_results]).to_csv(
    RESULT_DIR / "xgb_tuned_validation.csv",
    index=False
)

pd.Series(xgb_study.best_params, name="Value").to_csv(
    RESULT_DIR / "xgb_best_parameters.csv",
    index_label="Parameter"
)

,Model,Version,Feature_Set,ROC_AUC,Average_Precision,Log_Loss,Fit_Seconds,Prediction_Seconds,Tuning_Seconds
0,XGBoost,Tuned,Engineered + filtered,0.7646,0.2552,0.2441,30.498,0.1958,1829.0011

## LIGHT GBM

In [23]:
from lightgbm import LGBMClassifier

X_train = pd.read_csv(
    PROCESSED_DIR / "engineered" / "X_train.csv",
    dtype="float32"
)

X_valid = pd.read_csv(
    PROCESSED_DIR / "engineered" / "X_valid.csv",
    dtype="float32"
)

assert len(X_train) == len(y_train)
assert len(X_valid) == len(y_valid)
assert X_train.columns.equals(X_valid.columns)

print("Training:", X_train.shape)
print("Validation:", X_valid.shape)

Training: (215256, 320)
Validation: (46127, 320)

In [25]:
assert X_train.columns.equals(X_valid.columns)

safe_names = [f"feature_{i}" for i in range(X_train.shape[1])]

feature_mapping = pd.DataFrame({
    "Original_Name": X_train.columns,
    "LightGBM_Name": safe_names
})

feature_mapping.to_csv(
    ARTIFACT_DIR / "lgb_engineered_feature_mapping.csv",
    index=False
)

X_train.columns = safe_names
X_valid.columns = safe_names

print("Feature names updated. Values unchanged.")

Feature names updated. Values unchanged.

In [26]:
lgb_engineered = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    num_leaves=31,
    max_depth=-1,
    min_child_samples=20,
    subsample=1.0,
    colsample_bytree=1.0,
    objective="binary",
    random_state=SEED,
    n_jobs=4,
    verbosity=-1
)

start_time = time.perf_counter()

lgb_engineered.fit(X_train, y_train)

lgb_engineered_fit_seconds = time.perf_counter() - start_time

print(
    "Training time:",
    round(lgb_engineered_fit_seconds, 2),
    "seconds"
)

Training time: 10.0 seconds

In [27]:
start_time = time.perf_counter()

valid_probability = lgb_engineered.predict_proba(X_valid)[:, 1]

prediction_seconds = time.perf_counter() - start_time

lgb_engineered_results = {
    "Model": "LightGBM",
    "Feature_Set": "Engineered",
    "ROC_AUC": roc_auc_score(y_valid, valid_probability),
    "Average_Precision": average_precision_score(
        y_valid, valid_probability
    ),
    "Log_Loss": log_loss(y_valid, valid_probability),
    "Fit_Seconds": lgb_engineered_fit_seconds,
    "Prediction_Seconds": prediction_seconds
}

display(pd.DataFrame([lgb_engineered_results]).round(4))

joblib.dump(
    lgb_engineered,
    ARTIFACT_DIR / "lgb_engineered_baseline.joblib"
)

pd.DataFrame([lgb_engineered_results]).to_csv(
    RESULT_DIR / "lgb_engineered_baseline_validation.csv",
    index=False
)

,Model,Feature_Set,ROC_AUC,Average_Precision,Log_Loss,Fit_Seconds,Prediction_Seconds
0,LightGBM,Engineered,0.7609,0.2521,0.2452,10.0042,0.4699

In [ ]:
X_train = pd.read_csv(
    PROCESSED_DIR / "engineered_filtered" / "X_train.csv",
    dtype="float32"
)

X_valid = pd.read_csv(
    PROCESSED_DIR / "engineered_filtered" / "X_valid.csv",
    dtype="float32"
)

assert len(X_train) == len(y_train)
assert len(X_valid) == len(y_valid)
assert X_train.columns.equals(X_valid.columns)

safe_names = [f"feature_{i}" for i in range(X_train.shape[1])]

filtered_feature_mapping = pd.DataFrame({
    "Original_Name": X_train.columns,
    "LightGBM_Name": safe_names
})

filtered_feature_mapping.to_csv(
    ARTIFACT_DIR / "lgb_filtered_feature_mapping.csv",
    index=False
)

X_train.columns = safe_names
X_valid.columns = safe_names

lgb_filtered = LGBMClassifier(**lgb_engineered.get_params())

start_time = time.perf_counter()

lgb_filtered.fit(X_train, y_train)

lgb_filtered_fit_seconds = time.perf_counter() - start_time

print("Training features:", X_train.shape)
print(
    "Training time:",
    round(lgb_filtered_fit_seconds, 2),
    "seconds"
)

Training features: (215256, 264)
Training time: 9.56 seconds

In [30]:
start_time = time.perf_counter()

valid_probability = lgb_filtered.predict_proba(X_valid)[:, 1]

prediction_seconds = time.perf_counter() - start_time

lgb_filtered_results = {
    "Model": "LightGBM",
    "Feature_Set": "Engineered + filtered",
    "ROC_AUC": roc_auc_score(y_valid, valid_probability),
    "Average_Precision": average_precision_score(
        y_valid, valid_probability
    ),
    "Log_Loss": log_loss(y_valid, valid_probability),
    "Fit_Seconds": lgb_filtered_fit_seconds,
    "Prediction_Seconds": prediction_seconds
}

lgb_comparison = pd.DataFrame([
    lgb_engineered_results,
    lgb_filtered_results
]).sort_values("ROC_AUC", ascending=False)

display(lgb_comparison.round(4))

joblib.dump(
    lgb_filtered,
    ARTIFACT_DIR / "lgb_filtered_baseline.joblib"
)

lgb_comparison.to_csv(
    RESULT_DIR / "lgb_baseline_comparison.csv",
    index=False
)

,Model,Feature_Set,ROC_AUC,Average_Precision,Log_Loss,Fit_Seconds,Prediction_Seconds
1,LightGBM,Engineered + filtered,0.7614,0.2494,0.2452,9.5629,0.4408
0,LightGBM,Engineered,0.7609,0.2521,0.2452,10.0042,0.4699

In [31]:
def lgb_objective(trial):
    model = LGBMClassifier(
        n_estimators=trial.suggest_int(
            "n_estimators", 200, 1000, step=100
        ),
        learning_rate=trial.suggest_float(
            "learning_rate", 0.01, 0.15, log=True
        ),
        num_leaves=trial.suggest_int("num_leaves", 15, 127),
        max_depth=-1,
        min_child_samples=trial.suggest_int(
            "min_child_samples", 20, 150
        ),
        subsample=trial.suggest_float("subsample", 0.6, 1.0),
        subsample_freq=1,
        colsample_bytree=trial.suggest_float(
            "colsample_bytree", 0.6, 1.0
        ),
        reg_alpha=trial.suggest_float(
            "reg_alpha", 1e-4, 10, log=True
        ),
        reg_lambda=trial.suggest_float(
            "reg_lambda", 0.1, 20, log=True
        ),
        objective="binary",
        random_state=SEED,
        n_jobs=4,
        verbosity=-1
    )

    start = time.perf_counter()

    model.fit(X_train, y_train)
    probability = model.predict_proba(X_valid)[:, 1]

    trial.set_user_attr(
        "fit_predict_seconds",
        time.perf_counter() - start
    )

    return roc_auc_score(y_valid, probability)


lgb_study = optuna.create_study(
    study_name="lgb_engineered_filtered_v1",
    storage="sqlite:///" + database_path.as_posix(),
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=SEED),
    load_if_exists=True
)

tuning_start = time.perf_counter()

lgb_study.optimize(
    lgb_objective,
    timeout=30 * 60,
    n_jobs=1,
    gc_after_trial=True
)

lgb_tuning_seconds = time.perf_counter() - tuning_start

lgb_study.trials_dataframe().to_csv(
    RESULT_DIR / "lgb_optuna_trials.csv",
    index=False
)

print("Best validation ROC-AUC:", lgb_study.best_value)
print("Best parameters:", lgb_study.best_params)
print("Tuning seconds:", round(lgb_tuning_seconds, 2))

[I 2026-10-16 02:06:19,508] A new study created in RDB with name: lgb_engineered_filtered_v1
[I 2026-10-16 02:06:36,854] Trial 0 finished with value: 0.7314378519769631 and parameters: {'n_estimators': 500, 'learning_rate': 0.13125830316209655, 'num_leaves': 97, 'min_child_samples': 98, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'reg_alpha': 0.00019517224641449495, 'reg_lambda': 9.842315738502599}. Best is trial 0 with value: 0.7314378519769631.
[I 2026-10-16 02:06:48,660] Trial 1 finished with value: 0.7594988389878683 and parameters: {'n_estimators': 700, 'learning_rate': 0.06803900745073706, 'num_leaves': 17, 'min_child_samples': 147, 'subsample': 0.9329770563201687, 'colsample_bytree': 0.6849356442713105, 'reg_alpha': 0.0008111941985431928, 'reg_lambda': 0.26425260575499165}. Best is trial 1 with value: 0.7594988389878683.
[I 2026-10-16 02:07:00,726] Trial 2 finished with value: 0.7625543310538823 and parameters: {'n_estimators': 400, 'learning_rate': 0.04141536110538596, 'num_leaves': 63, 'min_child_samples': 58, 'subsample': 0.8447411578889518, 'colsample_bytree': 0.6557975442608167, 'reg_alpha': 0.0028888383623653178, 'reg_lambda': 0.6966418981413739}. Best is trial 2 with value: 0.7625543310538823.
[I 2026-10-16 02:07:15,758] Trial 3 finished with value: 0.7549552851946693 and parameters: {'n_estimators': 600, 'learning_rate': 0.0838375512850209, 'num_leaves': 37, 'min_child_samples': 87, 'subsample': 0.836965827544817, 'colsample_bytree': 0.6185801650879991, 'reg_alpha': 0.10907475835157694, 'reg_lambda': 0.24682044079890128}. Best is trial 2 with value: 0.7625543310538823.
[I 2026-10-16 02:07:26,902] Trial 4 finished with value: 0.7404566163050144 and parameters: {'n_estimators': 200, 'learning_rate': 0.13060986669773664, 'num_leaves': 124, 'min_child_samples': 125, 'subsample': 0.7218455076693483, 'colsample_bytree': 0.6390688456025535, 'reg_alpha': 0.2637333993381525, 'reg_lambda': 1.0299214204601976}. Best is trial 2 with value: 0.7625543310538823.
[I 2026-10-16 02:07:35,087] Trial 5 finished with value: 0.7627241252943188 and parameters: {'n_estimators': 300, 'learning_rate': 0.03822726574649208, 'num_leaves': 18, 'min_child_samples': 139, 'subsample': 0.7035119926400067, 'colsample_bytree': 0.8650089137415928, 'reg_alpha': 0.003618723330959626, 'reg_lambda': 1.572867419497858}. Best is trial 5 with value: 0.7627241252943188.
[I 2026-10-16 02:08:07,878] Trial 6 finished with value: 0.7625883760276472 and parameters: {'n_estimators': 600, 'learning_rate': 0.016497027917250065, 'num_leaves': 124, 'min_child_samples': 121, 'subsample': 0.9757995766256756, 'colsample_bytree': 0.9579309401710595, 'reg_alpha': 0.09761125443110447, 'reg_lambda': 13.220877067405619}. Best is trial 5 with value: 0.7627241252943188.
[I 2026-10-16 02:08:15,870] Trial 7 finished with value: 0.7534963985407979 and parameters: {'n_estimators': 200, 'learning_rate': 0.017001754132211097, 'num_leaves': 20, 'min_child_samples': 62, 'subsample': 0.7554709158757928, 'colsample_bytree': 0.7085396127095583, 'reg_alpha': 1.3921548533046495, 'reg_lambda': 0.6620642015198966}. Best is trial 5 with value: 0.7627241252943188.
[I 2026-10-16 02:08:28,191] Trial 8 finished with value: 0.763740135981806 and parameters: {'n_estimators': 400, 'learning_rate': 0.043477055106943, 'num_leaves': 30, 'min_child_samples': 125, 'subsample': 0.6298202574719083, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.7264803074826727, 'reg_lambda': 0.28658321062461245}. Best is trial 8 with value: 0.763740135981806.
[I 2026-10-16 02:08:38,062] Trial 9 finished with value: 0.7568229015168327 and parameters: {'n_estimators': 200, 'learning_rate': 0.09100328259258599, 'num_leaves': 94, 'min_child_samples': 115, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'reg_alpha': 0.006199100007802264, 'reg_lambda': 0.18476435128841198}. Best is trial 8 with value: 0.763740135981806.
[I 2026-10-16 02:08:56,142] Trial 10 finished with value: 0.7635164498651158 and parameters: {'n_estimators': 400, 'learning_rate': 0.01737111971967549, 'num_leaves': 72, 'min_child_samples': 101, 'subsample': 0.6358406055425909, 'colsample_bytree': 0.9780546176921546, 'reg_alpha': 0.028143640331431317, 'reg_lambda': 0.7940699914751019}. Best is trial 8 with value: 0.763740135981806.
[I 2026-10-16 02:09:12,501] Trial 11 finished with value: 0.7523778223036273 and parameters: {'n_estimators': 400, 'learning_rate': 0.06002578430659176, 'num_leaves': 86, 'min_child_samples': 116, 'subsample': 0.6096892900648527, 'colsample_bytree': 0.9904664086315051, 'reg_alpha': 0.5612380731275525, 'reg_lambda': 0.20712750916650402}. Best is trial 8 with value: 0.763740135981806.
[I 2026-10-16 02:09:27,493] Trial 12 finished with value: 0.7619556689352255 and parameters: {'n_estimators': 400, 'learning_rate': 0.014875787822012399, 'num_leaves': 38, 'min_child_samples': 108, 'subsample': 0.6504025410999158, 'colsample_bytree': 0.9857727054863911, 'reg_alpha': 0.10419642446852193, 'reg_lambda': 0.22761736449745232}. Best is trial 8 with value: 0.763740135981806.
[I 2026-10-16 02:09:50,720] Trial 13 finished with value: 0.764097753860058 and parameters: {'n_estimators': 500, 'learning_rate': 0.015703029528389124, 'num_leaves': 89, 'min_child_samples': 111, 'subsample': 0.6344184799355105, 'colsample_bytree': 0.9894622689655921, 'reg_alpha': 0.016252918803428804, 'reg_lambda': 1.9200265830027896}. Best is trial 13 with value: 0.764097753860058.
[I 2026-10-16 02:10:07,468] Trial 14 finished with value: 0.7624314689750105 and parameters: {'n_estimators': 400, 'learning_rate': 0.036262442783837445, 'num_leaves': 51, 'min_child_samples': 121, 'subsample': 0.7037114050715503, 'colsample_bytree': 0.981114520694381, 'reg_alpha': 8.958491866177857, 'reg_lambda': 1.2090874354272763}. Best is trial 13 with value: 0.764097753860058.
[I 2026-10-16 02:10:38,030] Trial 15 finished with value: 0.7635151706454915 and parameters: {'n_estimators': 600, 'learning_rate': 0.018201231854021862, 'num_leaves': 106, 'min_child_samples': 131, 'subsample': 0.6850981021044502, 'colsample_bytree': 0.9833312997216431, 'reg_alpha': 0.016125534527387783, 'reg_lambda': 5.911780968606702}. Best is trial 13 with value: 0.764097753860058.
[I 2026-10-16 02:10:57,722] Trial 16 finished with value: 0.7631409799070568 and parameters: {'n_estimators': 600, 'learning_rate': 0.025465194613343577, 'num_leaves': 52, 'min_child_samples': 148, 'subsample': 0.6041226124261373, 'colsample_bytree': 0.9967066056400297, 'reg_alpha': 0.0006476729574340807, 'reg_lambda': 1.9958224740925752}. Best is trial 13 with value: 0.764097753860058.
[I 2026-10-16 02:11:11,872] Trial 17 finished with value: 0.7628862885464021 and parameters: {'n_estimators': 400, 'learning_rate': 0.032931240234449044, 'num_leaves': 44, 'min_child_samples': 117, 'subsample': 0.609941820305658, 'colsample_bytree': 0.915539046927274, 'reg_alpha': 0.11036200674632528, 'reg_lambda': 0.4450577523806986}. Best is trial 13 with value: 0.764097753860058.
[I 2026-10-16 02:11:34,843] Trial 18 finished with value: 0.762214406936177 and parameters: {'n_estimators': 500, 'learning_rate': 0.021245340244211805, 'num_leaves': 91, 'min_child_samples': 124, 'subsample': 0.6005425953855322, 'colsample_bytree': 0.8771813582505139, 'reg_alpha': 0.5030102643077916, 'reg_lambda': 0.43178567163235115}. Best is trial 13 with value: 0.764097753860058.
[I 2026-10-16 02:12:01,118] Trial 19 finished with value: 0.7635975283247721 and parameters: {'n_estimators': 600, 'learning_rate': 0.011327213244500927, 'num_leaves': 61, 'min_child_samples': 111, 'subsample': 0.6893184333249202, 'colsample_bytree': 0.9314163780464395, 'reg_alpha': 0.024380729562245112, 'reg_lambda': 2.703475707822993}. Best is trial 13 with value: 0.764097753860058.
[I 2026-10-16 02:12:20,428] Trial 20 finished with value: 0.7634894722631369 and parameters: {'n_estimators': 400, 'learning_rate': 0.026886326274710236, 'num_leaves': 63, 'min_child_samples': 137, 'subsample': 0.6678379020038259, 'colsample_bytree': 0.9892986090766251, 'reg_alpha': 6.762044677880226, 'reg_lambda': 0.10398070660708322}. Best is trial 13 with value: 0.764097753860058.
[I 2026-10-16 02:12:46,038] Trial 21 finished with value: 0.7637608251427603 and parameters: {'n_estimators': 600, 'learning_rate': 0.013691677960074417, 'num_leaves': 92, 'min_child_samples': 149, 'subsample': 0.6325008142522417, 'colsample_bytree': 0.9091953784116459, 'reg_alpha': 0.0050100307530925965, 'reg_lambda': 2.7587285159112374}. Best is trial 13 with value: 0.764097753860058.
[I 2026-10-16 02:13:14,412] Trial 22 finished with value: 0.7639906793778374 and parameters: {'n_estimators': 700, 'learning_rate': 0.01553243647478639, 'num_leaves': 115, 'min_child_samples': 141, 'subsample': 0.6783873670638281, 'colsample_bytree': 0.8735949156254219, 'reg_alpha': 0.011362739410365617, 'reg_lambda': 2.6553901246358556}. Best is trial 13 with value: 0.764097753860058.
[I 2026-10-16 02:13:42,933] Trial 23 finished with value: 0.7637810583442446 and parameters: {'n_estimators': 700, 'learning_rate': 0.015593135952913641, 'num_leaves': 106, 'min_child_samples': 144, 'subsample': 0.6957987790509733, 'colsample_bytree': 0.8764994906188855, 'reg_alpha': 0.0009212082824953248, 'reg_lambda': 2.9878266776806504}. Best is trial 13 with value: 0.764097753860058.
[I 2026-10-16 02:14:12,923] Trial 24 finished with value: 0.7631960623441489 and parameters: {'n_estimators': 700, 'learning_rate': 0.01274349688620732, 'num_leaves': 124, 'min_child_samples': 111, 'subsample': 0.7155906381247461, 'colsample_bytree': 0.907996906168441, 'reg_alpha': 0.0036938579951511018, 'reg_lambda': 1.1877043397647449}. Best is trial 13 with value: 0.764097753860058.
[I 2026-10-16 02:14:42,363] Trial 25 finished with value: 0.7641832335951545 and parameters: {'n_estimators': 700, 'learning_rate': 0.010991004482532927, 'num_leaves': 110, 'min_child_samples': 115, 'subsample': 0.7475526413173819, 'colsample_bytree': 0.8516656929039618, 'reg_alpha': 0.00044457234881545375, 'reg_lambda': 2.2632671673251044}. Best is trial 25 with value: 0.7641832335951545.
[I 2026-10-16 02:15:13,439] Trial 26 finished with value: 0.7639823074553452 and parameters: {'n_estimators': 800, 'learning_rate': 0.011949047257239422, 'num_leaves': 107, 'min_child_samples': 136, 'subsample': 0.7607131277687614, 'colsample_bytree': 0.9297942052506434, 'reg_alpha': 0.0024151183344229147, 'reg_lambda': 1.0512804102614473}. Best is trial 25 with value: 0.7641832335951545.
[I 2026-10-16 02:15:47,086] Trial 27 finished with value: 0.763325966463725 and parameters: {'n_estimators': 900, 'learning_rate': 0.01270239880754719, 'num_leaves': 113, 'min_child_samples': 124, 'subsample': 0.7271303101003402, 'colsample_bytree': 0.7901242103625382, 'reg_alpha': 0.011962855421635856, 'reg_lambda': 2.012251606109712}. Best is trial 25 with value: 0.7641832335951545.
[I 2026-10-16 02:16:08,927] Trial 28 finished with value: 0.764047148691651 and parameters: {'n_estimators': 600, 'learning_rate': 0.016409630575342244, 'num_leaves': 100, 'min_child_samples': 142, 'subsample': 0.68244320052025, 'colsample_bytree': 0.7757069456815063, 'reg_alpha': 0.021510675440665275, 'reg_lambda': 1.3818198321725421}. Best is trial 25 with value: 0.7641832335951545.
[I 2026-10-16 02:16:33,490] Trial 29 finished with value: 0.7643650157699916 and parameters: {'n_estimators': 600, 'learning_rate': 0.013575368819245742, 'num_leaves': 99, 'min_child_samples': 125, 'subsample': 0.638064571868125, 'colsample_bytree': 0.7657207522772916, 'reg_alpha': 0.00991609595269129, 'reg_lambda': 6.046009275006006}. Best is trial 29 with value: 0.7643650157699916.
[I 2026-10-16 02:17:02,592] Trial 30 finished with value: 0.7640302781912582 and parameters: {'n_estimators': 600, 'learning_rate': 0.010791958211285854, 'num_leaves': 99, 'min_child_samples': 122, 'subsample': 0.6936324671443769, 'colsample_bytree': 0.7457439166277762, 'reg_alpha': 0.0003232647477529254, 'reg_lambda': 2.757072050194571}. Best is trial 29 with value: 0.7643650157699916.
[I 2026-10-16 02:17:35,419] Trial 31 finished with value: 0.7636201426479334 and parameters: {'n_estimators': 700, 'learning_rate': 0.020131989041681477, 'num_leaves': 105, 'min_child_samples': 140, 'subsample': 0.6938411816319747, 'colsample_bytree': 0.7194732896383903, 'reg_alpha': 0.004004687427609835, 'reg_lambda': 6.501712436774186}. Best is trial 29 with value: 0.7643650157699916.
[I 2026-10-16 02:18:03,926] Trial 32 finished with value: 0.7644985295687056 and parameters: {'n_estimators': 600, 'learning_rate': 0.01128652456006213, 'num_leaves': 92, 'min_child_samples': 143, 'subsample': 0.6758237105918393, 'colsample_bytree': 0.7870352950980741, 'reg_alpha': 0.002375105682265333, 'reg_lambda': 1.2793850664403816}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:18:27,012] Trial 33 finished with value: 0.7638716549578385 and parameters: {'n_estimators': 600, 'learning_rate': 0.012330345169742156, 'num_leaves': 95, 'min_child_samples': 130, 'subsample': 0.6805576660851756, 'colsample_bytree': 0.8378006649679344, 'reg_alpha': 0.0033122821387864066, 'reg_lambda': 0.8272843821441207}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:18:50,981] Trial 34 finished with value: 0.7638399151125056 and parameters: {'n_estimators': 600, 'learning_rate': 0.013080889324380222, 'num_leaves': 87, 'min_child_samples': 132, 'subsample': 0.7262478395791527, 'colsample_bytree': 0.8011684236771246, 'reg_alpha': 0.00012584586048326537, 'reg_lambda': 0.9890862576751195}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:19:19,262] Trial 35 finished with value: 0.7643918287199396 and parameters: {'n_estimators': 700, 'learning_rate': 0.011521136627476461, 'num_leaves': 107, 'min_child_samples': 104, 'subsample': 0.7233684186012475, 'colsample_bytree': 0.8851946803348043, 'reg_alpha': 0.00030128579200639356, 'reg_lambda': 5.382869569605009}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:19:43,839] Trial 36 finished with value: 0.763970173867225 and parameters: {'n_estimators': 600, 'learning_rate': 0.011507178439970093, 'num_leaves': 101, 'min_child_samples': 87, 'subsample': 0.6552862997325773, 'colsample_bytree': 0.8720631446830205, 'reg_alpha': 0.00027630257998111204, 'reg_lambda': 4.920840604072997}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:20:07,847] Trial 37 finished with value: 0.7631335579001272 and parameters: {'n_estimators': 600, 'learning_rate': 0.017091880496607297, 'num_leaves': 102, 'min_child_samples': 114, 'subsample': 0.772164378638882, 'colsample_bytree': 0.8910562626388212, 'reg_alpha': 0.0009885519285883874, 'reg_lambda': 4.732959731769293}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:20:31,986] Trial 38 finished with value: 0.7636016762893958 and parameters: {'n_estimators': 600, 'learning_rate': 0.016100061116955666, 'num_leaves': 87, 'min_child_samples': 112, 'subsample': 0.6731779493784896, 'colsample_bytree': 0.8231402674546504, 'reg_alpha': 0.0005181598975827147, 'reg_lambda': 3.105329289538}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:21:00,180] Trial 39 finished with value: 0.7642255554998554 and parameters: {'n_estimators': 600, 'learning_rate': 0.012929402422710885, 'num_leaves': 94, 'min_child_samples': 143, 'subsample': 0.6380840437897131, 'colsample_bytree': 0.8499026820719334, 'reg_alpha': 0.0006150726338797573, 'reg_lambda': 1.0260942792898853}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:21:20,354] Trial 40 finished with value: 0.762413673890137 and parameters: {'n_estimators': 400, 'learning_rate': 0.011889988334886758, 'num_leaves': 93, 'min_child_samples': 149, 'subsample': 0.6906343115985866, 'colsample_bytree': 0.8391579629695329, 'reg_alpha': 0.00041294123892454026, 'reg_lambda': 0.9874237702866139}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:21:49,157] Trial 41 finished with value: 0.7634760277915404 and parameters: {'n_estimators': 500, 'learning_rate': 0.010746291859035178, 'num_leaves': 107, 'min_child_samples': 140, 'subsample': 0.7206618209050684, 'colsample_bytree': 0.7554570831365887, 'reg_alpha': 0.001068587529431539, 'reg_lambda': 2.9312563482654155}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:22:29,799] Trial 42 finished with value: 0.7633339014250582 and parameters: {'n_estimators': 800, 'learning_rate': 0.014102832460573676, 'num_leaves': 101, 'min_child_samples': 129, 'subsample': 0.709288402144015, 'colsample_bytree': 0.8299990485791953, 'reg_alpha': 0.001450957682666081, 'reg_lambda': 0.9692956086476887}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:23:04,712] Trial 43 finished with value: 0.7643018210539945 and parameters: {'n_estimators': 700, 'learning_rate': 0.012728748571267885, 'num_leaves': 122, 'min_child_samples': 98, 'subsample': 0.6989983429935615, 'colsample_bytree': 0.8458734421259687, 'reg_alpha': 0.0001539268185995404, 'reg_lambda': 1.933324035452433}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:23:33,952] Trial 44 finished with value: 0.7642002117526441 and parameters: {'n_estimators': 700, 'learning_rate': 0.010438677438817122, 'num_leaves': 120, 'min_child_samples': 102, 'subsample': 0.6709927754313401, 'colsample_bytree': 0.8874255992967741, 'reg_alpha': 0.0001305685512008965, 'reg_lambda': 3.4548841993790806}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:24:02,581] Trial 45 finished with value: 0.7635605386127631 and parameters: {'n_estimators': 700, 'learning_rate': 0.012748007016645113, 'num_leaves': 108, 'min_child_samples': 96, 'subsample': 0.717947457588927, 'colsample_bytree': 0.8804687266894896, 'reg_alpha': 0.00018129094530164333, 'reg_lambda': 7.375462130300611}. Best is trial 32 with value: 0.7644985295687056.
[I 2026-10-16 02:24:29,114] Trial 46 finished with value: 0.7647266486246882 and parameters: {'n_estimators': 600, 'learning_rate': 0.012981647389531049, 'num_leaves': 112, 'min_child_samples': 141, 'subsample': 0.6728797803085103, 'colsample_bytree': 0.8221922485426718, 'reg_alpha': 0.00015732454116579086, 'reg_lambda': 1.628392582373205}. Best is trial 46 with value: 0.7647266486246882.
[I 2026-10-16 02:25:00,082] Trial 47 finished with value: 0.7637588746494717 and parameters: {'n_estimators': 600, 'learning_rate': 0.013212294057681769, 'num_leaves': 101, 'min_child_samples': 133, 'subsample': 0.6850935088753874, 'colsample_bytree': 0.7867614234334749, 'reg_alpha': 0.0003455350562805402, 'reg_lambda': 1.00821728996655}. Best is trial 46 with value: 0.7647266486246882.
[I 2026-10-16 02:25:30,736] Trial 48 finished with value: 0.7636047856796707 and parameters: {'n_estimators': 600, 'learning_rate': 0.010088551152255643, 'num_leaves': 91, 'min_child_samples': 135, 'subsample': 0.6667866778078071, 'colsample_bytree': 0.8133537978526278, 'reg_alpha': 0.0003783297145940522, 'reg_lambda': 1.2592462597030818}. Best is trial 46 with value: 0.7647266486246882.
[I 2026-10-16 02:25:58,556] Trial 49 finished with value: 0.7631996656905166 and parameters: {'n_estimators': 600, 'learning_rate': 0.011110182293225175, 'num_leaves': 92, 'min_child_samples': 137, 'subsample': 0.6237259294581343, 'colsample_bytree': 0.8322698572607657, 'reg_alpha': 0.0009029678580666357, 'reg_lambda': 3.4836271155414873}. Best is trial 46 with value: 0.7647266486246882.
[I 2026-10-16 02:26:31,972] Trial 50 finished with value: 0.7645687156632438 and parameters: {'n_estimators': 700, 'learning_rate': 0.012242987398982138, 'num_leaves': 102, 'min_child_samples': 99, 'subsample': 0.702400499365184, 'colsample_bytree': 0.8075731594637348, 'reg_alpha': 0.00012494350006192744, 'reg_lambda': 5.275216874629517}. Best is trial 46 with value: 0.7647266486246882.

Best validation ROC-AUC: 0.7651776748665996
Best parameters: {'n_estimators': 600, 'learning_rate': 0.013533950488442989, 'num_leaves': 95, 'min_child_samples': 144, 'subsample': 0.6530740311316475, 'colsample_bytree': 0.7860198467382739, 'reg_alpha': 0.0008533477368853772, 'reg_lambda': 1.8738619464917554}
Tuning seconds: 1820.31

In [32]:
lgb_tuned = LGBMClassifier(
    **lgb_study.best_params,
    max_depth=-1,
    subsample_freq=1,
    objective="binary",
    random_state=SEED,
    n_jobs=4,
    verbosity=-1
)

start_time = time.perf_counter()

lgb_tuned.fit(X_train, y_train)

lgb_tuned_fit_seconds = time.perf_counter() - start_time

start_time = time.perf_counter()

valid_probability = lgb_tuned.predict_proba(X_valid)[:, 1]

prediction_seconds = time.perf_counter() - start_time

lgb_tuned_results = {
    "Model": "LightGBM",
    "Version": "Tuned",
    "Feature_Set": "Engineered + filtered",
    "ROC_AUC": roc_auc_score(y_valid, valid_probability),
    "Average_Precision": average_precision_score(
        y_valid, valid_probability
    ),
    "Log_Loss": log_loss(y_valid, valid_probability),
    "Fit_Seconds": lgb_tuned_fit_seconds,
    "Prediction_Seconds": prediction_seconds,
    "Tuning_Seconds": lgb_tuning_seconds
}

display(pd.DataFrame([lgb_tuned_results]).round(4))

joblib.dump(
    lgb_tuned,
    ARTIFACT_DIR / "lgb_filtered_tuned.joblib"
)

pd.DataFrame([lgb_tuned_results]).to_csv(
    RESULT_DIR / "lgb_tuned_validation.csv",
    index=False
)

pd.Series(lgb_study.best_params, name="Value").to_csv(
    RESULT_DIR / "lgb_best_parameters.csv",
    index_label="Parameter"
)

,Model,Version,Feature_Set,ROC_AUC,Average_Precision,Log_Loss,Fit_Seconds,Prediction_Seconds,Tuning_Seconds
0,LightGBM,Tuned,Engineered + filtered,0.7652,0.2552,0.2441,21.3769,1.9395,1820.3074

## CATBOOST

In [33]:
from catboost import CatBoostClassifier

X_train = pd.read_csv(
    PROCESSED_DIR / "engineered" / "X_train.csv",
    dtype="float32"
)

X_valid = pd.read_csv(
    PROCESSED_DIR / "engineered" / "X_valid.csv",
    dtype="float32"
)

assert len(X_train) == len(y_train)
assert len(X_valid) == len(y_valid)
assert X_train.columns.equals(X_valid.columns)

print("Training:", X_train.shape)
print("Validation:", X_valid.shape)

Training: (215256, 320)
Validation: (46127, 320)

In [34]:
cat_baseline_params = {
    "iterations": 300,
    "learning_rate": 0.05,
    "depth": 6,
    "loss_function": "Logloss",
    "eval_metric": "AUC",
    "random_seed": SEED,
    "thread_count": 4,
    "verbose": False,
    "allow_writing_files": False
}

cat_engineered = CatBoostClassifier(**cat_baseline_params)

start_time = time.perf_counter()

cat_engineered.fit(X_train, y_train)

cat_engineered_fit_seconds = time.perf_counter() - start_time

print("Training seconds:", round(cat_engineered_fit_seconds, 2))

Training seconds: 29.01

In [35]:
start_time = time.perf_counter()

valid_probability = cat_engineered.predict_proba(X_valid)[:, 1]

prediction_seconds = time.perf_counter() - start_time

cat_engineered_results = {
    "Model": "CatBoost",
    "Feature_Set": "Engineered",
    "ROC_AUC": roc_auc_score(y_valid, valid_probability),
    "Average_Precision": average_precision_score(
        y_valid, valid_probability
    ),
    "Log_Loss": log_loss(y_valid, valid_probability),
    "Fit_Seconds": cat_engineered_fit_seconds,
    "Prediction_Seconds": prediction_seconds
}

display(pd.DataFrame([cat_engineered_results]).round(4))

joblib.dump(
    cat_engineered,
    ARTIFACT_DIR / "cat_engineered_baseline.joblib"
)

pd.DataFrame([cat_engineered_results]).to_csv(
    RESULT_DIR / "cat_engineered_baseline_validation.csv",
    index=False
)

,Model,Feature_Set,ROC_AUC,Average_Precision,Log_Loss,Fit_Seconds,Prediction_Seconds
0,CatBoost,Engineered,0.7619,0.2537,0.2449,29.0052,0.0504

In [36]:
X_train = pd.read_csv(
    PROCESSED_DIR / "engineered_filtered" / "X_train.csv",
    dtype="float32"
)

X_valid = pd.read_csv(
    PROCESSED_DIR / "engineered_filtered" / "X_valid.csv",
    dtype="float32"
)

assert len(X_train) == len(y_train)
assert len(X_valid) == len(y_valid)
assert X_train.columns.equals(X_valid.columns)

cat_filtered = CatBoostClassifier(**cat_baseline_params)

start_time = time.perf_counter()

cat_filtered.fit(X_train, y_train)

cat_filtered_fit_seconds = time.perf_counter() - start_time

print("Training seconds:", round(cat_filtered_fit_seconds, 2))

Training seconds: 24.5

In [37]:
start_time = time.perf_counter()

valid_probability = cat_filtered.predict_proba(X_valid)[:, 1]

prediction_seconds = time.perf_counter() - start_time

cat_filtered_results = {
    "Model": "CatBoost",
    "Feature_Set": "Engineered + filtered",
    "ROC_AUC": roc_auc_score(y_valid, valid_probability),
    "Average_Precision": average_precision_score(
        y_valid, valid_probability
    ),
    "Log_Loss": log_loss(y_valid, valid_probability),
    "Fit_Seconds": cat_filtered_fit_seconds,
    "Prediction_Seconds": prediction_seconds
}

cat_comparison = pd.DataFrame([
    cat_engineered_results,
    cat_filtered_results
]).sort_values("ROC_AUC", ascending=False)

display(cat_comparison.round(4))

joblib.dump(
    cat_filtered,
    ARTIFACT_DIR / "cat_filtered_baseline.joblib"
)

cat_comparison.to_csv(
    RESULT_DIR / "cat_baseline_comparison.csv",
    index=False
)

,Model,Feature_Set,ROC_AUC,Average_Precision,Log_Loss,Fit_Seconds,Prediction_Seconds
1,CatBoost,Engineered + filtered,0.7628,0.2562,0.2446,24.4953,0.0441
0,CatBoost,Engineered,0.7619,0.2537,0.2449,29.0052,0.0504

In [38]:
if cat_filtered_results["ROC_AUC"] > cat_engineered_results["ROC_AUC"]:
    cat_feature_folder = "engineered_filtered"
    cat_feature_label = "Engineered + filtered"
    cat_selected_baseline = cat_filtered_results
else:
    cat_feature_folder = "engineered"
    cat_feature_label = "Engineered"
    cat_selected_baseline = cat_engineered_results

X_train = pd.read_csv(
    PROCESSED_DIR / cat_feature_folder / "X_train.csv",
    dtype="float32"
)

X_valid = pd.read_csv(
    PROCESSED_DIR / cat_feature_folder / "X_valid.csv",
    dtype="float32"
)

print("Selected:", cat_feature_label)
print("Baseline validation ROC-AUC:", cat_selected_baseline["ROC_AUC"])

Selected: Engineered + filtered
Baseline validation ROC-AUC: 0.7627637494388215

In [40]:
def cat_objective(trial):
    model = CatBoostClassifier(
        iterations=trial.suggest_int(
            "iterations", 200, 1000, step=100
        ),
        learning_rate=trial.suggest_float(
            "learning_rate", 0.01, 0.15, log=True
        ),
        depth=trial.suggest_int("depth", 4, 8),
        l2_leaf_reg=trial.suggest_float(
            "l2_leaf_reg", 1, 30, log=True
        ),
        random_strength=trial.suggest_float(
            "random_strength", 0.01, 10, log=True
        ),
        bootstrap_type="Bayesian",
        bagging_temperature=trial.suggest_float(
            "bagging_temperature", 0, 5
        ),
        loss_function="Logloss",
        eval_metric="AUC",
        random_seed=SEED,
        thread_count=4,
        verbose=False,
        allow_writing_files=False
    )

    start = time.perf_counter()

    model.fit(X_train, y_train)
    probability = model.predict_proba(X_valid)[:, 1]

    trial.set_user_attr(
        "fit_predict_seconds",
        time.perf_counter() - start
    )

    return roc_auc_score(y_valid, probability)

In [41]:
cat_study = optuna.create_study(
    study_name=f"cat_onehot_{cat_feature_folder}_v1",
    storage="sqlite:///" + database_path.as_posix(),
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=SEED),
    load_if_exists=True
)

tuning_start = time.perf_counter()

cat_study.optimize(
    cat_objective,
    timeout=30 * 60,
    n_jobs=1,
    gc_after_trial=True
)

cat_tuning_seconds = time.perf_counter() - tuning_start

cat_study.trials_dataframe().to_csv(
    RESULT_DIR / "cat_optuna_trials.csv",
    index=False
)

print("Best validation ROC-AUC:", cat_study.best_value)
print("Best parameters:", cat_study.best_params)
print("Tuning seconds:", round(cat_tuning_seconds, 2))

[I 2026-10-16 02:41:30,831] Using an existing study with `study_name='cat_onehot_engineered_filtered_v1'` instead of creating a new one.
[I 2026-10-16 02:42:16,771] Trial 0 finished with value: 0.762559213619874 and parameters: {'iterations': 500, 'learning_rate': 0.13125830316209655, 'depth': 7, 'l2_leaf_reg': 7.6611007077713635, 'random_strength': 0.02938027938703535, 'bagging_temperature': 0.7799726016810132}. Best is trial 0 with value: 0.762559213619874.
[I 2026-10-16 02:42:36,015] Trial 1 finished with value: 0.7525799833336682 and parameters: {'iterations': 200, 'learning_rate': 0.10440040750544663, 'depth': 7, 'l2_leaf_reg': 11.114989443094977, 'random_strength': 0.011527987128232402, 'bagging_temperature': 4.8495492608099715}. Best is trial 0 with value: 0.762559213619874.
[I 2026-10-16 02:43:31,775] Trial 2 finished with value: 0.7545914485358672 and parameters: {'iterations': 900, 'learning_rate': 0.01777174904859463, 'depth': 4, 'l2_leaf_reg': 1.8659959624904914, 'random_strength': 0.08179499475211674, 'bagging_temperature': 2.6237821581611893}. Best is trial 0 with value: 0.762559213619874.
[I 2026-10-16 02:44:24,775] Trial 3 finished with value: 0.7589666012981218 and parameters: {'iterations': 500, 'learning_rate': 0.022004527434741072, 'depth': 7, 'l2_leaf_reg': 1.6071238512039876, 'random_strength': 0.07523742884534858, 'bagging_temperature': 1.8318092164684585}. Best is trial 0 with value: 0.762559213619874.
[I 2026-10-16 02:45:05,388] Trial 4 finished with value: 0.7638123928922707 and parameters: {'iterations': 600, 'learning_rate': 0.0838375512850209, 'depth': 4, 'l2_leaf_reg': 5.748924681991978, 'random_strength': 0.59874749104614, 'bagging_temperature': 0.23225206359998862}. Best is trial 4 with value: 0.7638123928922707.
[I 2026-10-16 02:45:50,089] Trial 5 finished with value: 0.7468234696929947 and parameters: {'iterations': 700, 'learning_rate': 0.015869086642715014, 'depth': 4, 'l2_leaf_reg': 25.212679047779208, 'random_strength': 7.886714129990489, 'bagging_temperature': 4.041986740582305}. Best is trial 4 with value: 0.7638123928922707.
[I 2026-10-16 02:46:30,261] Trial 6 finished with value: 0.7522829700683126 and parameters: {'iterations': 400, 'learning_rate': 0.01302780710309028, 'depth': 7, 'l2_leaf_reg': 4.468467502504582, 'random_strength': 0.023233503515390115, 'bagging_temperature': 2.475884550556351}. Best is trial 4 with value: 0.7638123928922707.
[I 2026-10-16 02:46:45,452] Trial 7 finished with value: 0.7570753827406117 and parameters: {'iterations': 200, 'learning_rate': 0.1173393765991262, 'depth': 5, 'l2_leaf_reg': 9.51975448269268, 'random_strength': 0.08612579192594885, 'bagging_temperature': 2.600340105889054}. Best is trial 4 with value: 0.7638123928922707.
[I 2026-10-16 02:48:00,564] Trial 8 finished with value: 0.7502957973734353 and parameters: {'iterations': 600, 'learning_rate': 0.016497027917250065, 'depth': 8, 'l2_leaf_reg': 13.962563737015762, 'random_strength': 6.58410616012161, 'bagging_temperature': 4.474136752138244}. Best is trial 4 with value: 0.7638123928922707.
[I 2026-10-16 02:48:45,889] Trial 9 finished with value: 0.7623001906442537 and parameters: {'iterations': 700, 'learning_rate': 0.12139707695554378, 'depth': 4, 'l2_leaf_reg': 1.9475582306295418, 'random_strength': 0.013667272915456224, 'bagging_temperature': 1.6266516538163218}. Best is trial 4 with value: 0.7638123928922707.
[I 2026-10-16 02:49:07,845] Trial 10 finished with value: 0.7575784263587332 and parameters: {'iterations': 300, 'learning_rate': 0.03137987255292731, 'depth': 4, 'l2_leaf_reg': 8.27024723039054, 'random_strength': 0.8666260074275023, 'bagging_temperature': 0.14835572202680775}. Best is trial 4 with value: 0.7638123928922707.
[I 2026-10-16 02:49:49,092] Trial 11 finished with value: 0.763793198265135 and parameters: {'iterations': 400, 'learning_rate': 0.09333059979216937, 'depth': 7, 'l2_leaf_reg': 9.881337291436695, 'random_strength': 0.4272793025058393, 'bagging_temperature': 0.025512019645331452}. Best is trial 4 with value: 0.7638123928922707.
[I 2026-10-16 02:50:33,436] Trial 12 finished with value: 0.7646378758489742 and parameters: {'iterations': 500, 'learning_rate': 0.05495327281382541, 'depth': 6, 'l2_leaf_reg': 6.968578231260249, 'random_strength': 0.3413366679758341, 'bagging_temperature': 0.16070798359536803}. Best is trial 12 with value: 0.7646378758489742.
[I 2026-10-16 02:51:19,390] Trial 13 finished with value: 0.7625417225079807 and parameters: {'iterations': 700, 'learning_rate': 0.05926492397105001, 'depth': 5, 'l2_leaf_reg': 16.970363678066082, 'random_strength': 0.16886371266621042, 'bagging_temperature': 1.3370527248254822}. Best is trial 12 with value: 0.7646378758489742.
[I 2026-10-16 02:52:02,851] Trial 14 finished with value: 0.7648220708093405 and parameters: {'iterations': 700, 'learning_rate': 0.06661254248904148, 'depth': 5, 'l2_leaf_reg': 2.2400769991602094, 'random_strength': 0.4052338268652721, 'bagging_temperature': 0.339101338813105}. Best is trial 14 with value: 0.7648220708093405.
[I 2026-10-16 02:52:45,175] Trial 15 finished with value: 0.7637061100063522 and parameters: {'iterations': 700, 'learning_rate': 0.0918846754315516, 'depth': 5, 'l2_leaf_reg': 1.1323835575117664, 'random_strength': 0.7643970867070413, 'bagging_temperature': 0.3435858641582024}. Best is trial 14 with value: 0.7648220708093405.
[I 2026-10-16 02:53:11,567] Trial 16 finished with value: 0.762214406936177 and parameters: {'iterations': 400, 'learning_rate': 0.04054715547975812, 'depth': 5, 'l2_leaf_reg': 1.5329964420411826, 'random_strength': 0.8407391357270211, 'bagging_temperature': 0.2332245789531271}. Best is trial 14 with value: 0.7648220708093405.
[I 2026-10-16 02:54:03,121] Trial 17 finished with value: 0.7641732024868131 and parameters: {'iterations': 700, 'learning_rate': 0.08276722932517987, 'depth': 5, 'l2_leaf_reg': 1.306524475559197, 'random_strength': 0.1097997260893911, 'bagging_temperature': 0.6217945588588372}. Best is trial 14 with value: 0.7648220708093405.
[I 2026-10-16 02:55:09,763] Trial 18 finished with value: 0.7641827649701437 and parameters: {'iterations': 900, 'learning_rate': 0.09057221643671856, 'depth': 5, 'l2_leaf_reg': 3.6530851928059507, 'random_strength': 0.3594745443437948, 'bagging_temperature': 0.7552494667668033}. Best is trial 14 with value: 0.7648220708093405.
[I 2026-10-16 02:55:53,662] Trial 19 finished with value: 0.7633503792936849 and parameters: {'iterations': 600, 'learning_rate': 0.043988896649790055, 'depth': 5, 'l2_leaf_reg': 3.371252620728946, 'random_strength': 0.16890821813487494, 'bagging_temperature': 0.40731454641466525}. Best is trial 14 with value: 0.7648220708093405.
[I 2026-10-16 02:56:37,053] Trial 20 finished with value: 0.7633613666503594 and parameters: {'iterations': 400, 'learning_rate': 0.07219842362353956, 'depth': 7, 'l2_leaf_reg': 4.467251621962425, 'random_strength': 0.3866062350942195, 'bagging_temperature': 0.559880584990722}. Best is trial 14 with value: 0.7648220708093405.
[I 2026-10-16 02:57:36,223] Trial 21 finished with value: 0.7643431107171171 and parameters: {'iterations': 800, 'learning_rate': 0.10407707447184049, 'depth': 5, 'l2_leaf_reg': 4.3318019236192224, 'random_strength': 0.08192917701272655, 'bagging_temperature': 0.4580704204288793}. Best is trial 14 with value: 0.7648220708093405.
[I 2026-10-16 02:58:41,922] Trial 22 finished with value: 0.7640717578374936 and parameters: {'iterations': 900, 'learning_rate': 0.04781605296359733, 'depth': 5, 'l2_leaf_reg': 2.2934007226161315, 'random_strength': 0.18457306231027587, 'bagging_temperature': 1.176859666250861}. Best is trial 14 with value: 0.7648220708093405.
[I 2026-10-16 02:59:50,086] Trial 23 finished with value: 0.757963914759593 and parameters: {'iterations': 800, 'learning_rate': 0.13803033610685078, 'depth': 6, 'l2_leaf_reg': 2.828380665846898, 'random_strength': 0.14857479228815995, 'bagging_temperature': 0.5111106774520717}. Best is trial 14 with value: 0.7648220708093405.
[I 2026-10-16 03:00:41,964] Trial 24 finished with value: 0.7645518831594739 and parameters: {'iterations': 700, 'learning_rate': 0.07124552497195684, 'depth': 5, 'l2_leaf_reg': 2.9952309538346653, 'random_strength': 0.33568851774025316, 'bagging_temperature': 0.6966949460887686}. Best is trial 14 with value: 0.7648220708093405.
[I 2026-10-16 03:01:42,313] Trial 25 finished with value: 0.7657613029882849 and parameters: {'iterations': 700, 'learning_rate': 0.051367912293047865, 'depth': 6, 'l2_leaf_reg': 2.53181575966548, 'random_strength': 0.4861048354419499, 'bagging_temperature': 0.20104346523931832}. Best is trial 25 with value: 0.7657613029882849.
[I 2026-10-16 03:02:35,096] Trial 26 finished with value: 0.763935172645127 and parameters: {'iterations': 700, 'learning_rate': 0.06110808876796462, 'depth': 5, 'l2_leaf_reg': 1.6656275639156304, 'random_strength': 3.0109344102421676, 'bagging_temperature': 0.4391911873549346}. Best is trial 25 with value: 0.7657613029882849.
[I 2026-10-16 03:03:11,395] Trial 27 finished with value: 0.7638159265781637 and parameters: {'iterations': 400, 'learning_rate': 0.05566514436734145, 'depth': 6, 'l2_leaf_reg': 2.4636341752235995, 'random_strength': 0.28823929983922686, 'bagging_temperature': 0.4546527468960991}. Best is trial 25 with value: 0.7657613029882849.
[I 2026-10-16 03:04:14,539] Trial 28 finished with value: 0.7643221492470348 and parameters: {'iterations': 700, 'learning_rate': 0.0633751890842686, 'depth': 7, 'l2_leaf_reg': 2.895083888408418, 'random_strength': 0.1984473743211444, 'bagging_temperature': 0.7264060532310379}. Best is trial 25 with value: 0.7657613029882849.
[I 2026-10-16 03:05:05,460] Trial 29 finished with value: 0.7649303041885476 and parameters: {'iterations': 700, 'learning_rate': 0.07815875639033153, 'depth': 6, 'l2_leaf_reg': 4.908952577062831, 'random_strength': 0.14813114695936178, 'bagging_temperature': 0.3430663847869922}. Best is trial 25 with value: 0.7657613029882849.
[I 2026-10-16 03:05:48,601] Trial 30 finished with value: 0.7634204513983555 and parameters: {'iterations': 600, 'learning_rate': 0.07857125801812749, 'depth': 6, 'l2_leaf_reg': 2.8833278053344724, 'random_strength': 0.11423759102496513, 'bagging_temperature': 1.4166329623393317}. Best is trial 25 with value: 0.7657613029882849.
[I 2026-10-16 03:06:39,176] Trial 31 finished with value: 0.7634614180901869 and parameters: {'iterations': 700, 'learning_rate': 0.0845778891207855, 'depth': 6, 'l2_leaf_reg': 2.107955677692963, 'random_strength': 0.3532768856455109, 'bagging_temperature': 0.08384799070929116}. Best is trial 25 with value: 0.7657613029882849.
[I 2026-10-16 03:07:23,111] Trial 32 finished with value: 0.7643730267245699 and parameters: {'iterations': 600, 'learning_rate': 0.06366428455918167, 'depth': 6, 'l2_leaf_reg': 5.197996403534509, 'random_strength': 0.04921475221743236, 'bagging_temperature': 0.5241996210109627}. Best is trial 25 with value: 0.7657613029882849.
[I 2026-10-16 03:08:21,383] Trial 33 finished with value: 0.7646287059974097 and parameters: {'iterations': 800, 'learning_rate': 0.08936582582684723, 'depth': 6, 'l2_leaf_reg': 10.868404543576982, 'random_strength': 0.12633709699298282, 'bagging_temperature': 0.5285174639928305}. Best is trial 25 with value: 0.7657613029882849.
[I 2026-10-16 03:09:22,801] Trial 34 finished with value: 0.76488803294601 and parameters: {'iterations': 700, 'learning_rate': 0.05504257258058057, 'depth': 6, 'l2_leaf_reg': 1.064125321887436, 'random_strength': 0.27838567332418573, 'bagging_temperature': 0.31695398957289084}. Best is trial 25 with value: 0.7657613029882849.
[I 2026-10-16 03:10:08,851] Trial 35 finished with value: 0.7640317917233881 and parameters: {'iterations': 600, 'learning_rate': 0.05053320548041851, 'depth': 5, 'l2_leaf_reg': 2.4578456679569025, 'random_strength': 0.4548576161005672, 'bagging_temperature': 0.031026348423870587}. Best is trial 25 with value: 0.7657613029882849.
[I 2026-10-16 03:10:59,459] Trial 36 finished with value: 0.762862508993484 and parameters: {'iterations': 700, 'learning_rate': 0.06416062652701954, 'depth': 5, 'l2_leaf_reg': 1.5397105977543972, 'random_strength': 0.36947541467827516, 'bagging_temperature': 1.2983305723437764}. Best is trial 25 with value: 0.7657613029882849.
[I 2026-10-16 03:12:15,313] Trial 37 finished with value: 0.7634159424658181 and parameters: {'iterations': 900, 'learning_rate': 0.0843428413834184, 'depth': 6, 'l2_leaf_reg': 1.1401933466528043, 'random_strength': 0.18317905249261163, 'bagging_temperature': 0.9868928189283837}. Best is trial 25 with value: 0.7657613029882849.

Best validation ROC-AUC: 0.7657613029882849
Best parameters: {'iterations': 700, 'learning_rate': 0.051367912293047865, 'depth': 6, 'l2_leaf_reg': 2.53181575966548, 'random_strength': 0.4861048354419499, 'bagging_temperature': 0.20104346523931832}
Tuning seconds: 1844.64

In [42]:
cat_tuned = CatBoostClassifier(
    **cat_study.best_params,
    bootstrap_type="Bayesian",
    loss_function="Logloss",
    eval_metric="AUC",
    random_seed=SEED,
    thread_count=4,
    verbose=False,
    allow_writing_files=False
)

start_time = time.perf_counter()

cat_tuned.fit(X_train, y_train)

cat_tuned_fit_seconds = time.perf_counter() - start_time

start_time = time.perf_counter()

valid_probability = cat_tuned.predict_proba(X_valid)[:, 1]

prediction_seconds = time.perf_counter() - start_time

cat_tuned_results = {
    "Model": "CatBoost",
    "Version": "Tuned",
    "Feature_Set": cat_feature_label,
    "ROC_AUC": roc_auc_score(y_valid, valid_probability),
    "Average_Precision": average_precision_score(
        y_valid, valid_probability
    ),
    "Log_Loss": log_loss(y_valid, valid_probability),
    "Fit_Seconds": cat_tuned_fit_seconds,
    "Prediction_Seconds": prediction_seconds,
    "Tuning_Seconds": cat_tuning_seconds
}

display(pd.DataFrame([cat_tuned_results]).round(4))

joblib.dump(
    cat_tuned,
    ARTIFACT_DIR / f"cat_{cat_feature_folder}_tuned.joblib"
)

pd.DataFrame([cat_tuned_results]).to_csv(
    RESULT_DIR / "cat_tuned_validation.csv",
    index=False
)

pd.Series(cat_study.best_params, name="Value").to_csv(
    RESULT_DIR / "cat_best_parameters.csv",
    index_label="Parameter"
)

,Model,Version,Feature_Set,ROC_AUC,Average_Precision,Log_Loss,Fit_Seconds,Prediction_Seconds,Tuning_Seconds
0,CatBoost,Tuned,Engineered + filtered,0.7658,0.2563,0.2437,53.1228,0.0369,1844.6371